import { type NextPage } from "next";
import Head from "next/head";
import { Layout, Space, Button, ConfigProvider, Spin } from "antd";
import {
  Bars3BottomLeftIcon,
  ArrowDownTrayIcon,
  FunnelIcon,
} from "@heroicons/react/24/outline";

import { api } from "~/utils/api";
import ChartCard from "~/components/ChartCard";
import ChartOne from "~/components/ChartOne";
import ChartTwo from "~/components/ChartTwo";

const Home: NextPage = () => {
  const { data, isLoading, error } = api.covid.getCovidData.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "white",
            colorText: "#c7d2fe",
            colorBorder: "#c7d2fe",
          },
        }}
      >
        <Layout
          className="h-full pt-4"
          style={{
            background: "linear-gradient(to right, #0f0c29, #302b63, #24243e)",
          }}
        >
          <Layout.Header className="flex items-center justify-between bg-transparent">
            <h1 className="text-xl font-bold">My neat little demo</h1>
            <Space>
              <Button className="flex items-center justify-between gap-2 px-4 py-2 font-medium">
                Export to PDF
                <ArrowDownTrayIcon className="h-5 w-5" />
              </Button>
              <Button className="flex items-center justify-between gap-2 px-4 py-2 font-medium">
                Notes<span className="opacity-75">(3)</span>
                <Bars3BottomLeftIcon className="h-5 w-5" />
              </Button>
              <Button className="flex items-center justify-between gap-2 px-4 py-2 font-medium">
                Filter
                <div className="h-5 w-5 rounded-full bg-indigo-400 p-1 text-[0.75rem] leading-none text-white">
                  9+
                </div>
                <FunnelIcon className="h-5 w-5" />
              </Button>
            </Space>
          </Layout.Header>
          <Layout.Content>
            <div className="m-8 flex flex-col gap-8 lg:mx-12 lg:my-16 lg:flex-row">
              <ChartCard title="New cases">
                {isLoading && (
                  <div className="relative flex h-[564px] items-center justify-center">
                    <Spin tip="Loading" className="my-auto" />
                  </div>
                )}
                {data && <ChartOne data={data.byNations} />}
                {error && "Oooopsie! Something went wrong :("}
              </ChartCard>
              <ChartCard title="Cases by nation">
                {isLoading && (
                  <div className="relative flex h-[564px] items-center justify-center">
                    <Spin tip="Loading" className="my-auto" />
                  </div>
                )}
                {data && <ChartTwo data={data.cumulative} />}
                {error && "Oooopsie! Something went wrong :("}
              </ChartCard>
            </div>
          </Layout.Content>
        </Layout>
      </ConfigProvider>
    </>
  );
};

export default Home;
